apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/service.yaml
  - resources/service-monitor.yaml
