apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-benchmark-exporter-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
