apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fio-benchmark-exporter
  labels:
    app: fio-benchmark-exporter
spec:
  selector:
    matchLabels:
      app: fio-benchmark-exporter
  endpoints:
  - port: metrics
    path: /metrics
